### ISSUE TITLE
unable to compile on mac 10.11 --- bison: invalid option -- W

### ISSUE THREAD

**Issue by k2patel** [zevweiss/enthrall#3]
mac:enthrall test$ make
	    YACC: cfg-parse.tab.c
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/bison: invalid option -- W
Try `/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/bison --help' for more information.
	    YACC: cfg-parse.tab.c
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/bison: invalid option -- W
Try `/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/bison --help' for more information.

mac:enthrall test$ brew install bison
Warning: bison-3.0.4 already installed

**Comment by zevweiss** [comment]
Hi, thanks for the report.  Are you certain you have the homebrew version of bison earlier in your path than the Apple-provided one?  (I get a successful build on OSX with bison 3.0.4.)

Run `which -a bison` and if it shows `/usr/bin/bison` before `/usr/local/bin/bison` (or wherever homebrew's version is installed) you'll need to adjust your `$PATH` to fix it.  (Or alternately run `make` with the `BISON` variable set to the one you want to use, e.g. `make BISON=/usr/local/bin/bison`.)

**Comment by k2patel** [comment]
Hi,

Thanks that worked.
